### PR TITLE
feat: update HPA api to v2 for K8s 1.24+

### PR DESCRIPTION
**Pull request by DavidSpek**
Fixes: https://github.com/bentoml/Yatai/issues/449

This PR updates the HPA version used by the backend from `v2beta2` to `v2` to support newer versions of Kubernetes. Note: this does mean that Kubernetes `v1.23.0` will be the new minimum supported version. Since Kubernetes `v1.27.0` was recently released I believe this shouldn't be a large problem.

Related to: https://github.com/bentoml/Yatai/pull/463

### CODE REVIEW

**Comment by yetone** [comment]
Thank you for your contribution! We want to be forward compatible because our commitment is to support v1.20+ and we need to make sure that users of v1.20 ~ v1.23 versions of k8s can continue to use yatai-deployment

**Comment by FogDong** [comment]
Hi @DavidSpek , thanks for the contribution!

As yetone said, we'd like to ensure the compatibility so instead of the chaging the apiversion, maybe we need to use some conversion to handle the issue.
I'd like to continue to take over this issue and cherry pick your commit if you don't mind.

**Comment by DavidSpek** [comment]
Feel free to cherry pick my commit from this PR and other ones. I haven't actually used Yatai yet but I saw this would become a problem for us and many others in the near future so wanted to get the ball rolling on a fix.

**Comment by DavidSpek** [comment]
Closed as implemented in https://github.com/bentoml/yatai-deployment/pull/114.

**Pull request closed without merging**
